### PR TITLE
Store language

### LINKED ISSUE #248: userstores in national language
Hello,

nice work!!!, but I've a problem ....

The userstores are always be created in english (foldernames like "Inbox").
i've tried to change them to german, but no success.

Is there any way to set the to german, so folders are created like "Posteingang"?

### PR DESCRIPTION
**Pull request by fbartels**
Fixes #248

### CODE REVIEW

**Comment by fbartels** [comment]
Language selection seems broken upstream: https://jira.kopano.io/browse/KC-1607

**Comment by XtraLarge** [comment]
Sorry, but I've freshed pulled your  repository, and configured it incl. demo-ldap. I've noticed the new configuration variable in the .env file. I've filled it with "MAILBOXLANG=de_DE.UTF-8".
Then I've logged in with user user0 in kopano-webapp and the inbox folder named "Inbox" not "Posteingang". 

Is there a bug or did I forget something?

best regards

Willi Werres

**Comment by fbartels** [comment]
as you can see in my second comment in this pull request:

> Language selection seems broken upstream: https://jira.kopano.io/browse/KC-1607

The ticket is fixed, but a nightly with the required fix did not make it to the public, yet.

when using the supported kopano packages (which is recommended anyways) you should be good, though.

**Comment by XtraLarge** [comment]
How do I change to the supported kopano images? .... and must I have a license to use it?

**Comment by fbartels** [comment]
Yes, you need a subscription. Everything else is documented at https://github.com/zokradonh/kopano-docker#how-to-use-the-project-with-the-official-and-supported-kopano-releases

**Pull request merged**
