### PR TITLE
Double quotes not needed by docker compose

### PR DESCRIPTION
**Pull request by zokradonh**
Same issue as https://github.com/zokradonh/kopano-docker/issues/216

### CODE REVIEW

**Comment by fbartels** [comment]
@zokradonh can you rebase against master? afterwards the test should continue further than the linting check.

While I am not sure if this really makes a difference (I just tested against ldap, but did not notice something out of the ordinary with it) I am quite sure that it makes a difference for the bash scripting and will then throw the same errors as in the linked ticket.

**Comment by zokradonh** [comment]
This variable is never used in bash, is it?

OpenLDAP is default setting. The kcconf.py script does not work with the double quotes according to my tests. It worked after removing them.

**Comment by fbartels** [comment]
No, not used in any of the bash scripts, but the whole file is sourced which will throw an error (based on experience, have not tested this change though).

> The kcconf.py script does not work with the double quotes according to my tests. It worked after removing them.

Hmm.. Maybe some tests would be in order to check config files after startup.

**Comment by fbartels** [comment]
I have remodeled the package selection and fixed the errors thrown in version.sh

edit: for whatever reason my last local commit is not pushed here.. will take a closer look tomorrow (was wrong remote).

**Comment by fbartels** [comment]
Tests currently fail, since the nightly builds are not available. currently running the tests locally against the supported packages. will merge later if they succeed.

**Pull request merged**
