### PR TITLE
enable proxy mode for self service

### PR DESCRIPTION
**Pull request by cguentherTUChemnitz**
i am discussing the correct creation of urls in the mail send by the self-service here:
https://github.com/tiredofit/docker-self-service-password/issues/11

necessary fixes are collected in this pull-request

### CODE REVIEW

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz,

as far as I can see there is still some movement in the docker image. is that correct?

**Comment by cguentherTUChemnitz** [comment]
Hi @fbartels, sry for my absence in the last time. I am really busy right know. So i am not able to fix the problem by myself, as well the maintainer seems also to be too busy at the moment to fix it himself. So i would propose, that we deactivate the mail-based self-service and keep only the website-based reset, as long as the url is not embedded correctly in the mail.

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz ,

no problem. I've glanced over the env variables of the docker image, but could not directly find a "set this env to disable password reset via email" env.

I'd propose to just keep this as it is for now.

**Comment by fbartels** [comment]
I have added some additional lint checks. Please rebase.

**Comment by fbartels** [comment]
closing this for now

**Pull request closed without merging**
