### PR TITLE
basis for discussion: make portmapping switchable

### PR DESCRIPTION
**Pull request by cguentherTUChemnitz**
**move portmapping into docker-compose.portmapping.yml and load it automatically**

This changeset enables the possiblity to switch off all host port mappings without patching the docker-compose.yml. Only the COMPOSE_FILE list has to be patched in the .env.

**content of this PR:**
This PR does not change the behavior of this kopano stack. Only the portmapping part is splitted up.

Ensure loading of docker-compose.portmapping.yml via COMPOSE_FILE in .env. This disables the override automatism and starts only when the override.yml exists. This problem is bypassed by enforcing the creation an empty override.yml during setup.sh.

### CODE REVIEW

**Comment by fbartels** [comment]
@cguentherTUChemnitz can you rebase on top of https://github.com/zokradonh/kopano-docker/pull/173 to see if that fixes the travis failure of this pr?

**Comment by cguentherTUChemnitz** [comment]
> @cguentherTUChemnitz can you rebase on top of #173 to see if that fixes the travis failure of this pr?

Thanks for your quick fix!

**Comment by fbartels** [comment]
@zokradonh what do you think?

It feels to me like before merging something like this we would need to think about an update strategy for people just doing a git pull.

**Comment by cguentherTUChemnitz** [comment]
> It feels to me like before merging something like this we would need to think about an update strategy for people just doing a git pull.

This is really a good and non trivial point, to ensure an existing docker-compose.override.yml for those who had run setup.sh earlier.

**Comment by fbartels** [comment]
Not only that, the COMPOSE_FILE also needs to be in .env for ports to stay exposed for existing setups.

**Comment by cguentherTUChemnitz** [comment]
Okay, that seems like a general discussion about an update / upgrade path, where changes in the already generated .env is necessary to fit the upgraded version of the stack. So do i see it right, that the update path via git pull is currently only possible, if the setup.sh would generate the same entries in the global .env file? This does not look very easy, since this would involves patching of the existing config file, which could be modified by the user earlier on.

**Comment by fbartels** [comment]
has been merged in #182

**Pull request closed without merging**
