### PR TITLE
Make it possible for users to customise exposed ports

### PR DESCRIPTION
**Pull request by fbartels**
My take on #171

### CODE REVIEW

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz,

I have taken your approach and made some adjustments to it. What do you think if this?

Pinging previous contributors for additional feedback: @mithomas @mhoffmann75 @nupplaphil

**Comment by mhoffmann75** [comment]
Although this makes the whole project a bit more complex, I like the idea. I really appreciate the addition to setup.sh for adding missing values. We should keep this up for further changes, too.

However, maybe we should point out preferred way of ignoring docker-compose.portmapping.yml, in the docs, as adding it to .gitignore most probably won't work as it is overridden on next pull... Maybe .git/info/exclude could come to the rescue here ?

**Comment by fbartels** [comment]
Yes, that is a good point with ignoring it. One idea would be to exclude a folder like `~/local-config` and ask users to put their files into this.

**Comment by cguentherTUChemnitz** [comment]
Sorry for the delay, i am currently really packed with work.  Thanks @fbartels for taking my thoughts a step further ;) It seems pretty nice for me with the documentation you already added.

**Comment by fbartels** [comment]
After a bit more thinking the easiest is to just instruct users to put these local port modifications into the override file. instructions have been update. will merge now.

**Pull request merged**
