### PR TITLE
Use variables to check if the server is running

### PR DESCRIPTION
**Pull request by RobinvG**
Add server_socket variables so we can use another name then kopano_server as the server name

### CODE REVIEW

**Comment by fbartels** [comment]
Hi @RobinvG,

I was wondering if there is a way to simplify the environment variables until I realised that this way the same env variable is used in the configuration file for the socket this way. I like that.

The downside is that this does not seem to work for dockerize:

```
kopano_gateway_1    | 2019-11-27T15:58:39.422520256Z 2019/11/27 15:58:39 Waiting for http://kopano_server:236/: unexpected HTTP status code: 405.
kopano_ical_1       | 2019-11-27T15:58:20.360662763Z 2019/11/27 15:58:20 Waiting for http://kopano_server:236/: unexpected HTTP status code: 405.
```

**Comment by fbartels** [comment]
Maybe this needs a single "KOPANO_CONN" after all. Then there is one place where one can check if the variable begins with with "http", replace "http*://" with "tcp://" and finally assign this value to KCCONF_*_SERVER_SOCKET.

**Comment by fbartels** [comment]
@RobinvG what do you think about https://github.com/zokradonh/kopano-docker/pull/298 ?

I think this approach may be less confusing down the road.

**Comment by RobinvG** [comment]
@fbartels  I agree let's use that one then

**Comment by fbartels** [comment]
Great. Currently waiting for tests to finish, then I'll merge it.

**Pull request closed without merging**
